tools/replayer/src/replayer.c

Our fuzz tests pretend to be Doctest tests and thus need to ignore the
arguments CLion's test framework integration passes to such tests.
With this commit and #19, play buttons are on fuzz tests in CLion
successfully trigger a regression test run on the seed corpus, with
command output shown in a console. The test status is currently shown
as "testing framework exited unexpectedly" after the run, regardless of
whether the test passed or not. This will be improved in a follow-up PR.

replayer: Filter out CLion Doctest arguments

---

integration/cli_test.go
internal/cmd/root/root_test.go
tools/cmake/cmake_test.go
tools/replayer/replayer_test.go

This is based on #23 and should only be merged after #23 was merged.

Use fileutil.Cleanup to remove temporary directories in tests

---

internal/cmd/root/root.go
pkg/cmdutils/errors.go

We don't want to print the usage message on all unexpected errors, but
only for those errors which were caused by incorrect usage of the
command.

Reintroduce IncorrectUsageError

---

internal/cmd/run/run.go
tools/cmake/CIFuzz/share/CIFuzz/CIFuzzConfig.cmake
tools/cmake/CIFuzz/share/CIFuzz/CIFuzzFunctions.cmake
tools/cmake/cmake_test.go
tools/cmake/testdata/CMakeLists.txt
tools/cmake/testdata/src/parser/parser.cpp

Add the same compiler and linker options as are set for make
invocations when using clang or gcc and adapt the set of flags for
MSVC-style compilers.

cmake: Set compiler and linker options

---

pkg/runner/libfuzzer/libfuzzer_runner.go
pkg/runner/runnerutils.go

AFL++ fails with
Custom ASAN_OPTIONS set without abort_on_error=1 - please fix!
when abort_on_error=0 is set.

runner: Only set abort_on_error=0 when using libfuzzer

---

tools/cmake/cmake_test.go

5 minutes proved to be too short for some test runs on Windows.

Increase cmake_test timeout to 9 minutes

---

pkg/runfiles/finder.go

The path uses the lowercase "cifuzz" instead of "CIFuzz".

finder: Fix cifuzz include path

---

pkg/runner/libfuzzer/libfuzzer_runner.go
util/executil/executil.go

By using exec.CommandContext, two go routines were started which waited
for the context to be done, one from the exec package which immediately
sends a SIGKILL to the started process and one from the executil package
which first sends a SIGTERM to the process group and after a grace
period a SIGKILL.
As a result, the started process itself usually didn't have time to shut
down gracefully, because it received a SIGKILL at about the same time as
the SIGTERM.
To fix this, executil.CommandContext now doesn't use exec.CommandContext
anymore but exec.Command, so the exec package doesn't handle killing the
process anymore. Because callers expect that using
executil.CommandContext will terminate the process when the context is
done, the process group is now always terminated when the context is …

executil: Fix race when using CommandContext

---

README.md

We need LLVM, not just clang, and require version 11 for [`llvm-symbolizer --relativenames`](https://github.com/llvm/llvm-project/commit/21d9d0855be17220e869ef5bbec2d839fe841840)

readme: Mention that LLVM >= 11 is required

---

pkg/parser/libfuzzer/libfuzzer_parser.go
pkg/runner/libfuzzer/libfuzzer_runner.go

Without the stderr of the fuzzer printed during startup, it isn't
possible for users to understand why it exits abnormally, e.g. due to a
missing shared library dependency.
With this commit, the parsed output up to the point where the fuzzer has
been initialized is stored and made available to the runner to print in
case of an error.

runner: Print startup stderr in case of an unexpected exit error

---

integration-tests/cmake/cmake_test.go

integration-tests: Use deterministic random seed

---

pkg/runner/runnerutils.go
util/envutil/envutil.go
util/envutil/envutil_test.go

The purpose of the AddToColonSeparatedList function is to add paths to
the PATH or LD_LIBRARY_PATH environment variables, which are not
colon-separated on Windows, so we now use os.PathListSeparator instead.

envutil: Use os.PathListSeparator

---

pkg/runner/libfuzzer/integration-tests/crashing_corpus_entry_test.go
tools/install/installer.go
util/fileutil/fileutil.go

We've seen some errors in CI pipelines indicating that the files copied
by the installer are being used before they were synced to disk, so we
now sync after copying.
The Copy function from github.com/otiai10/copy already supports syncing
after copying, so we're using that now instead of fileutil.CopyFile.
Note that this might not fix all synchronization issues, quoting the
fsync(2) manual:
Calling fsync() does not necessarily ensure that the entry in the directory
containing the file has also reached disk.  For that an explicit fsync() on
a file descriptor for the directory is also needed.
So in case we still see synchronization issues, we should also call fsync
on the directory of the file we copied.

Call fsync after copying

---

internal/build/cmake/cmake.go

Speculative fix for https://github.com/CodeIntelligenceTesting/cifuzz/issues/105.

cmake: Emit cache args in deterministic order and remove spaces

---

internal/cmd/run/report_handler/report_handler.go
pkg/log/ptermwriter.go
pkg/runner/libfuzzer/integration-tests/asan_test.go
pkg/runner/libfuzzer/integration-tests/crashing_corpus_entry_test.go
pkg/runner/libfuzzer/integration-tests/empty_input_test.go
pkg/runner/libfuzzer/integration-tests/input_timeout_test.go
pkg/runner/libfuzzer/integration-tests/oom_test.go
pkg/runner/libfuzzer/integration-tests/slow_input_test.go
pkg/runner/libfuzzer/integration-tests/test_cases_written_to_corpus_test.go
pkg/runner/libfuzzer/integration-tests/testutils/runner_testutils.go
pkg/runner/libfuzzer/integration-tests/timeout_test.go
pkg/runner/libfuzzer/integration-tests/ubsan_non_recoverable_test.go
pkg/runner/libfuzzer/integration-tests/ubsan_recoverable_test.go
pkg/runner/libfuzzer/integration-tests/with_env_vars_test.go
pkg/runner/libfuzzer/integration-tests/with_file_accesses_test.go
pkg/runner/libfuzzer/libfuzzer_runner.go

Modifying the global variable os.Stderr caused "broken pipe" errors when
running the tests in parallel.

runner tests: Log to buffer instead modifying os.Stderr

---

integration-tests/cmake/cmake_test.go

Check that the fuzz test source file was actually modified. We are
seeing test failures on MacOS which could be caused by the source file
not being modified.

integration-tests: Avoid make not rebuilding fuzz test

---

integration-tests/cmake/cmake_test.go

This reverts commit dcc5fd2ab62b3476f9505f94e21cac619978ba9e.
This did not address the root cause of the integration test issue.

Revert "TMP: integration-tests: Close files eagerly"

---

pkg/runner/libfuzzer/integration-tests/crashing_corpus_entry_test.go
tools/install/installer.go

... because they don't fix the synchronization issues we were trying
to fix.
This reverts commits 373f2de1d840916ed7f1c3fc11d29e07b0dbe1e9 and
65b1930006a819dd56b0243e995fb1244cdd9833.

Revert commits which call sync or fsync

---

internal/build/cmake/cmake.go
util/executil/executil.go

The error handling logic is contained in a new executil helper function.

cmake: Print stderr on exec.Cmd failure

---

util/executil/executil.go

ExitError's are commonly encountered by users and already contain
enough context for debugging purposes that we don't need to emit stack
traces for them.

executil: Do not print a stack trace for ExitErrors

---

integration-tests/cmake/testdata/CMakeLists.txt
internal/cmd/init/init.go
tools/cmake/cifuzz/cmake/cifuzz-targets.cmake

Previously, projects with `project(MyProject LANGUAGES CXX)` in their
top-level CMakeLists.txt would fail to build the replayer.
This is fixed by marking replayer.c as a C++ source file if C is not
in ENABLED_LANGUAGES.

cmake: Fix for projects that don't enable the C language 

---

internal/cmd/run/run.go
pkg/runner/jazzer/jazzer_runner.go
pkg/runner/libfuzzer/integration-tests/crashing_corpus_entry_test.go
pkg/runner/libfuzzer/integration-tests/runner_testutils.go
pkg/runner/libfuzzer/libfuzzer_runner.go

If a seed corpus directory was specified via --seeds-dir, we used to
use that as the first corpus directory passed to libFuzzer, causing
libFuzzer to write generated inputs into that directory. We decided that
we always want to store generated inputs in a fixed, non-configurable
directory instead, so we now pass the directories specified via
--seeds-dir as additional corpus directories to libFuzzer.

run: Always use directory below .cifuzz-corpus as generated corpus dir

---

tools/cmake/cifuzz/include/cifuzz/cifuzz/cifuzz.h

Fixes https://github.com/CodeIntelligenceTesting/cifuzz/issues/142

cifuzz.h: Suppress unused argument warning for FUZZ_TEST_SETUP

---

internal/cmd/bundle/bundle.go
internal/cmd/create/create.go
internal/cmd/create/create_test.go
pkg/dialog/dialog.go
pkg/dialog/dialog_test.go
pkg/stubs/stubs.go
pkg/stubs/stubs_test.go

Use a default path instead. This reduces unnecessary complexity,
including having to test the shell completion support with different
shells. We also found that there is no popular tool which asks for the
path where it creates a file in a dialog.

dialog: Don't ask for file path in dialogs

---

tools/cmake/cifuzz/include/cifuzz/fuzzer/FuzzedDataProvider.h
tools/cmake/testdata/src/parser/parser_fuzz_test.cpp

Users can include it as usual via
`#include <fuzzer/FuzzedDataProvider.h>`.
Also adds a use of this header to the CMake tests.

cmake: Ship FuzzedDataProvider

---

integration-tests/cmake/cmake_test.go

Limiting runs rather than time should be less flaky and also provide
faster test failures in case of breakages.
The value of 1,000,000 runs is 5x as high as the maximum runs count
found in CI logs across the three platforms.

integration-tests: Limit runs rather than time

---

util/executil/executil_unix.go
util/executil/executil_windows.go

Fix for the following test failure seen in CI:
```
SUCCESS: The process with PID 3924 (child process of PID 5020) has been terminated.
SUCCESS: The process with PID 5020 (child process of PID 2564) has been terminated.
ERROR: The process "5020" not found.
cmake_test.go:86:
Error Trace:	D:\a\cifuzz\cifuzz\integration-tests\cmake\cmake_test.go:163
D:\a\cifuzz\cifuzz\integration-tests\cmake\cmake_test.go:86
Error:      	Received unexpected error:
exit status 128
code-intelligence.com/cifuzz/util/executil.(*Cmd).TerminateProcessGroup
D:/a/cifuzz/cifuzz/util/executil/executil_windows.go:18
code-intelligence.com/cifuzz/integration-tests/cmake.runFuzzer
D:/a/cifuzz/cifuzz/integration-tests/cmake/cmake_test.go:162
code-intelligence.com/cifuzz/integration-tests/cmake.TestIntegration_InitCreateRunBu …
```

util: Don't fail when trying to kill an already terminated process

---

go.mod
go.sum
tools/install/installer.go

This caused non-deterministic failures in tests which use the install
package.

installer: Fix race when running multiple installers in parallel

---

.gitignore
docs/Configuration.md
examples/cmake/cifuzz.yaml
integration-tests/cmake/cmake_test.go
internal/cmd/init/init.go
internal/cmd/root/root.go
internal/cmd/run/run.go
internal/cmd/run/run_test.go
internal/config/cifuzz.yaml.tmpl
internal/config/project.go
internal/config/project_test.go
pkg/cmdutils/pflag.go
pkg/runner/jazzer/jazzer_runner.go
pkg/runner/libfuzzer/integration-tests/runner_testutils.go
pkg/runner/libfuzzer/libfuzzer_runner.go

This uses viper to read the config file and set the command options
according to the settings in the config file. The commit also merges
the old project config into the command options struct, because the only
setting of the project config, the build system setting, can just as
well be a command option (and should also be configurable via a
command-line flag - that will be done in a follow-up commit).
Using viper allows us to handle configuration with very little
self-maintained code. What motivated me to make this change is the
viper.SetDefault() function, which allows us to set a default value
which is applied when neither the config file setting nor the flag is set,
a functionality that we would have reimplement otherwise.

Use viper to read cifuzz.yaml

---

pkg/minijail/output_filter.go
pkg/parser/libfuzzer/libfuzzer_parser.go
pkg/runner/libfuzzer/libfuzzer_runner.go

The line was misleading, causing users to wonder if minijail failed
when in fact it's the fuzzer which failed.

runner: Avoid printing "libminijail: child process exited with status"

---

pkg/parser/libfuzzer/libfuzzer_parser.go

... even though the corpus is non-empty.
The `err` value was overwritten, which affected the `err == nil` check
below.

run: Fix "Starting from enpty corpus" printed

---

pkg/parser/libfuzzer/libfuzzer_parser.go

As a follow-up to #166, this commit gets rid of an err == nil check that
made it important to not accidentally overwrite the value of err in the
err != nil branch.

parser: Refactor away error-prone err == nil check

---

integration-tests/make/make_test.go
pkg/minijail/output_filter.go

The pattern didn't match the line we want to filter.
Also, test that the line is filtered in an integration test.

minijail: Fix regex in output filter

---

integration-tests/cmake/cmake_test.go
internal/cmd/bundle/bundle.go
tools/cmake/cifuzz/cmake/cifuzz-functions.cmake

Makes it more clear that coverage builds essentially just use the
replayer (albeit with a few more, technical flags) and apply coverage
instrumentation.

cmake: Represent coverage builds as a combination of engine and sanitizer

---

tools/replayer/replayer_test.go
tools/replayer/src/replayer.c

will resolve compiler `-Wsign-conversion` warning and prevent `malloc(-1)` if `run_file` is called on a non-seekable file like `/dev/stdin`.

added error checking for ftell result

---

cmd/installer/installer.go

Consider the following scenario:
1. The installer fails to create a symlink to the first fpath directory
2. User follows the instructions to add the completion script to their fpath
3. The user runs a cifuzz installer again
4. The installer creates a symlink from the first fpath to the completion script.
The symlink created in step 4 creates a symlink loop, because the first fpath is the path to the completion script, so we create a symlink to itself. In effect, zsh hangs whenever the user opens a new shell.
This commit avoids creating such a symlink loop.

fix(installer): Fix zsh completion script symlink loop
